### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/edo#1584]
@AlexeyShok 
I have the agent who always takes blank 1st step search result (perhaps this is after I added location markup for him?).
This issue is reproduced for him only.
You can find the agent **fabirs10** in passbolt.

What is in logs:

`Supplier availability search exception on supplier 'https://etg-dev.happytravel.com/api/1.0/'Exception: 
System.ArgumentException: Invalid markup settings
   at HappyTravel.Edo.Api.Services.Markups.MarkupService.ApplyMarkups[TDetails](MarkupSubjectInfo subject, MarkupDestinationInfo destinationInfo, TDetails details, Func`3 priceProcessFunc, Action`1 logAction) in /src/Api/Services/Markups/MarkupService.cs:line 67
   at HappyTravel.Edo.Api.Services.Accommodations.Availability.PriceProcessor.ApplyMarkups[TDetails](MarkupSubjectInfo subjectInfo, TDetails details, Func`3 priceProcessFunc, Func`2 getMarkupDestinationFunc, Action`1 logAction) in /src/Api/Services/Accommodations/Availability/PriceProcessor.cs:line 42
   at HappyTravel.Edo.Api.Services.Accommodations.Availability.Steps.WideAvailabilitySearch.WideAvailabilityPriceProcessor.ApplyMarkups(List`1 results, AgentContext agent) in /src/Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/WideAvailabilityPriceProcessor.cs:line 31
   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.Map[T,K,E](Task`1 resultTask, Func`2 func)
   at CSharpFunctionalExtensions.AsyncResultExtensionsLeftOperand.Map[T,K,E](Task`1 resultTask, Func`2 func)
   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.Tap[T,E](Task`1 resultTask, Func`2 func)
   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.Tap[T,E](Task`1 resultTask, Func`1 func)
   at CSharpFunctionalExtensions.AsyncResultExtensionsLeftOperand.Finally[T,K,E](Task`1 resultTask, Func`2 func)
   at HappyTravel.Edo.Api.Services.Accommodations.Availability.Steps.WideAvailabilitySearch.WideAvailabilitySearchTask.Start(Guid searchId, AvailabilityRequest availabilityRequest, List`1 accommodationCodeMappings, SlimSupplier supplier, AgentContext agent, String languageCode, AccommodationBookingSettings searchSettings) in /src/Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/WideAvailabilitySearchTask.cs:line 177`

**Comment by DaniyarAskarov** [comment]
Case when markup's sum less than zero:
1) Logging
2) Set percentage sum to 0

**Comment by sergeyf-QA** [comment]
**Summary:**
- now if sum of markups is <0 then it sets as 0, so no markups are available in this case

**OK on DEV.**
